import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import AuthProvider from "./lib/next-auth";
import HeaderBtn from "./HeaderBtn";
import ReduxProvider from "../redux/provider";
import HeaderPart from "./HeaderPart";
import FooterPart from "./FooterPart";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "M-market",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderPart />
        <ReduxProvider>
          <div className="mainpart">
            <AuthProvider>{children}</AuthProvider>
          </div>
        </ReduxProvider>
        <FooterPart />
      </body>
    </html>
  );
}
