import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import AuthProvider from "./lib/next-auth";
import HeaderBtn from "./HeaderBtn";
import ReduxProvider from "../redux/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "M-market",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <div className="navbar">
            <Link href="/" className="logo">
              Home
            </Link>

            <Link href="/list">List</Link>
            <Link href="/cart">Cart</Link>

            <Link href="/board">Q&A</Link>
            <HeaderBtn />
          </div>
          <AuthProvider>{children}</AuthProvider>

          <div className="footer">Copyright 2024 by Moon</div>
        </ReduxProvider>
      </body>
    </html>
  );
}
