export const productData = {
  jacket: [
    {
      id: 1,
      product: "홍해인자켓",
      price: "20000",
      count: 1,
      img: "/img/jacket1.png",
    },
    {
      id: 2,
      product: "백현우자켓",
      price: "20000",
      count: 1,
    },
    {
      id: 3,
      product: "문씨집안자켓",
      price: "20000",
      count: 1,
    },
    {
      id: 4,
      product: "송하윤자켓",
      price: "20000",
      count: 1,
    },
    {
      id: 5,
      product: "웡카자켓",
      price: "20000",
      count: 1,
    },
    {
      id: 6,
      product: "티모시자켓",
      price: "20000",
      count: 1,
    },
    {
      id: 7,
      product: "어제산자켓",
      price: "20000",
      count: 1,
    },
    {
      id: 8,
      product: "내가제일잘나가자켓",
      price: "20000",
      count: 1,
    },
    {
      id: 9,
      product: "신상자켓",
      price: "20000",
      count: 1,
    },
  ],
  shoe: [
    {
      id: 1,
      product: "김말숙신발",
      price: "20000",
      count: 1,
    },
    {
      id: 2,
      product: "나이키신상신발",
      price: "20000",
      count: 1,
    },
    {
      id: 3,
      product: "나이키핫해",
      price: "20000",
      count: 1,
    },
    {
      id: 4,
      product: "아디다스저리가신발",
      price: "20000",
      count: 1,
    },
    {
      id: 5,
      product: "동묘신발",
      price: "20000",
      count: 1,
    },
    {
      id: 6,
      product: "내가어제산신발",
      price: "20000",
      count: 1,
    },
    {
      id: 7,
      product: "레거시신발",
      price: "20000",
      count: 1,
    },
    {
      id: 8,
      product: "뉴발",
      price: "20000",
      count: 1,
    },
    {
      id: 9,
      product: "발바리",
      price: "20000",
      count: 1,
    },
  ],
  cartItem: [
    {
      id: 1,
      product: "홍해인자켓",
      price: "20000",
      count: 1,
    },
    {
      id: 6,
      product: "티모시자켓",
      price: "20000",
      count: 1,
    },
    {
      id: 8,
      product: "뉴발",
      price: "20000",
      count: 1,
    },
  ],
};
